//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;

import javax.swing.*;
import javax.swing.event.*;

public class LoginScreen extends JPanel implements WindowListener, ActionListener{
    private JLabel userName;
    private JLabel password;
    private JPasswordField passwordSection;
    private JTextField usernameSection;
    private JButton LoginButton;
    private JLabel loginWelcome;
    private static JFrame frame=null;
    
   private  JPanel spanel;
    public LoginScreen() {
        /* //construct components
        userName = new JLabel ("Username:");
        password = new JLabel ("Password:");
        passwordSection = new JPasswordField (12);
        usernameSection = new JTextField (12);
        LoginButton = new JButton ("Login");
        loginWelcome = new JLabel ("WELCOME TO RECIPE GENERATOR");
        LoginButton.addActionListener(this);
        
        //adjust size and set layout
        setPreferredSize (new Dimension (656, 375));
        setBackground(Color.ORANGE);
        setLayout (null);

        //add components
        add (userName);
        add (password);
        add (passwordSection);
        add (usernameSection);
        add (LoginButton);
        add (loginWelcome);

        //set component bounds (only needed by Absolute Positioning)
        userName.setBounds (235, 100, 100, 25);
        password.setBounds (235, 135, 100, 25);
        passwordSection.setBounds (310, 135, 100, 25);
        usernameSection.setBounds (310, 100, 100, 25);
        LoginButton.setBounds (275, 195, 100, 25);
        loginWelcome.setBounds (230, 25, 200, 25);
        
        */
    }
    public void loginSignup(JPanel spanel)
    {
    	 
         
         invalidate(); validate(); // or ((JComponent) getContentPane()).revalidate();

         spanel.repaint(); //DO NOT FORGET REPAINT
    }
    
    @SuppressWarnings("deprecation")
	public void actionPerformed(ActionEvent e)
    {
    	Main2 frm = new Main2();
    	frame.dispose();
    	frm.setVisible(true);
    	frame.hide();
    	frame.setVisible(false);
    	
    }


	public void windowActivated(WindowEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	public void windowClosed(WindowEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	public void windowClosing(WindowEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	public void windowDeactivated(WindowEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	public void windowDeiconified(WindowEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	public void windowIconified(WindowEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	public void windowOpened(WindowEvent arg0) {
		// TODO Auto-generated method stub
		
	}
}
