//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;

import javax.swing.*;
import javax.swing.event.*;



public class Main2 extends JFrame{
	private JPanel main;
    private JLabel jcomp1;
    private JLabel jcomp2;
    private JLabel jcomp3;
    private JLabel jcomp4;
    private JLabel jcomp5;
    private JButton jcomp6;
    private JButton jcomp7;
    private JButton jcomp8;
    private JButton jcomp9;
    private JButton jcomp10;
    private JButton jcomp11;
    
    
    private JFrame frame = new JFrame();
    private JLayeredPane lpane = new JLayeredPane();
    private JPanel panelBlue = new JPanel();
    private JPanel panelGreen = new JPanel();
    public Main2()
    {
    	
        frame.setPreferredSize(new Dimension(600, 400));
       // frame.setLayout(new BorderLayout());
        frame.add(lpane, BorderLayout.CENTER);
        
        jcomp1 = new JLabel ("Main Menu");
        jcomp2 = new JLabel ("Recipe Generator");
        jcomp3 = new JLabel ("Feed");
        jcomp4 = new JLabel ("DENEMEE");
        jcomp5 = new JLabel ("newLabel");
        jcomp6 = new JButton ("My Favourite");
        jcomp7 = new JButton ("My Fridge");
        jcomp8 = new JButton ("Explore");
        jcomp9 = new JButton ("My Recipe");
        jcomp10 = new JButton ("Last Recipe");
        jcomp11 = new JButton ("Generate");
        jcomp7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent e) {
            	
            	panelBlue.remove(jcomp4);
            	lpane.add(panelGreen);
            	lpane.revalidate();
            }
        });
        
        lpane.setBounds(0, 0, 600, 400);
        
        jcomp1.setBounds (30, 20, 135, 30);
        jcomp2.setBounds (280, 20, 100, 25);
        jcomp3.setBounds (535, 15, 100, 25);
        jcomp4.setBounds (145, 60, 350, 270);
        jcomp5.setBounds (515, 65, 110, 250);
        jcomp6.setBounds (15, 75, 115, 25);
        jcomp7.setBounds (15, 115, 115, 25);
        jcomp8.setBounds (15, 155, 115, 25);
        jcomp9.setBounds (15, 195, 115, 25);
        jcomp10.setBounds (15, 235, 115, 25);
        jcomp11.setBounds (15, 275, 115, 25);
        panelBlue.add(jcomp1);
        panelBlue.add(jcomp2);
        panelBlue.add(jcomp3);
        panelBlue.add(jcomp4);
        panelBlue.add(jcomp5);
        panelBlue.add(jcomp6);
        panelBlue.add(jcomp7);
        panelBlue.add(jcomp8);
        panelBlue.add(jcomp9);
        panelBlue.add(jcomp10);
        panelBlue.add(jcomp11);
        panelBlue.setBounds(0, 0, 600, 400);
        panelBlue.setOpaque(true);
        panelBlue.setLayout(null);
        panelGreen.setBackground(Color.ORANGE);
        panelGreen.setBounds(145, 60, 350, 290);
        panelGreen.setOpaque(true);
        
        lpane.add(panelBlue, new Integer(0), 0);
        //lpane.add(panelGreen, new Integer(1), 0);
        frame.pack();
        frame.setVisible(true);
        
        ArrayList<JLabel> fridge = deneme.getFridge();
        	for(int i = 0; i< fridge.size();i++)
        		panelGreen.add(fridge.get(i));
    		
    		
    	
       
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        new Main2();
    }

}