//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;

import javax.swing.*;
import javax.swing.event.*;

public class Open extends JPanel implements WindowListener, ActionListener{
    /**
	 * 
	 */
	private static JButton SigninButton;
    private JLabel OpenWelcome;
    private static JButton SignupButton;
    private static JFrame frame=null;
    private static  LoginScreen frm2=null;
    private static  SignUpScreen frm=null;
    public Open() {
        //construct components
        SigninButton = new JButton ("SIGN IN");
        OpenWelcome = new JLabel ("WELCOME TO RECIPE GENERATOR");
        SignupButton = new JButton ("SIGN UP");
        SigninButton.addActionListener(this);
        SignupButton.addActionListener(this);
        //adjust size and set layout
        setPreferredSize (new Dimension (656, 375));
        setBackground(Color.ORANGE);
        setLayout (null);

        //add components
        add (SigninButton);
        add (OpenWelcome);
        add (SignupButton);

        //set component bounds (only needed by Absolute Positioning)
        SigninButton.setBounds (350, 230, 100, 25);
        OpenWelcome.setBounds (230, 35, 200, 25);
        SignupButton.setBounds (190, 230, 100, 25);
        
        
    }

    @SuppressWarnings("deprecation")
    
    public static void main (String[] args) {
        frame = new JFrame ("Welcome to Recipe Generator");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new Open());
        frame.pack();
        frame.setVisible (true);
        
    }
        
        public void actionPerformed(ActionEvent e){
        {
                if(SigninButton==e.getSource()){
                	frm2 = new LoginScreen();
                	
                	frm2.loginSignup(frm2);  
        	}
        	if(SignupButton==e.getSource()){
        			frm = new SignUpScreen();
        	    	       	    	
        	}
        }
    }

	public void windowActivated(WindowEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	public void windowClosed(WindowEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	public void windowClosing(WindowEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	public void windowDeactivated(WindowEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	public void windowDeiconified(WindowEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	public void windowIconified(WindowEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	public void windowOpened(WindowEvent arg0) {
		// TODO Auto-generated method stub
		
	}

}

