//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;

import javax.swing.*;
import javax.swing.event.*;

public class SignUpScreen extends JPanel implements WindowListener, ActionListener{
    private JLabel userName;
    private JLabel password;
    private JPasswordField passwordSection;
    private JTextField usernameSection;
    private JButton SigninButton;
    private JLabel loginWelcome;
    private JLabel jcomp7;
    private JTextField emailSection;
    private static JFrame frame=null;

    public SignUpScreen() {
        //construct components
        userName = new JLabel ("Username:");
        password = new JLabel ("Password:");
        passwordSection = new JPasswordField (12);
        usernameSection = new JTextField (12);
        SigninButton = new JButton ("Sign In");
        loginWelcome = new JLabel ("WELCOME TO RECIPE GENERATOR");
        jcomp7 = new JLabel ("E-mail:");
        emailSection = new JTextField (12);
        SigninButton.addActionListener(this);

        //adjust size and set layout
        setPreferredSize (new Dimension (656, 375));
        setBackground(Color.ORANGE);
        setLayout (null);

        //add components
        add (userName);
        add (password);
        add (passwordSection);
        add (usernameSection);
        add (SigninButton);
        add (loginWelcome);
        add (jcomp7);
        add (emailSection);

        //set component bounds (only needed by Absolute Positioning)
        userName.setBounds (235, 100, 100, 25);
        password.setBounds (235, 135, 100, 25);
        passwordSection.setBounds (310, 135, 100, 25);
        usernameSection.setBounds (310, 100, 100, 25);
        SigninButton.setBounds (285, 230, 100, 25);
        loginWelcome.setBounds (230, 25, 200, 25);
        jcomp7.setBounds (235, 175, 100, 25);
        emailSection.setBounds (310, 175, 100, 25);
    }
    
    public void actionPerformed(ActionEvent e)
    {
    	Main2 frm = new Main2();
    	frame.dispose();
    	frm.setVisible(true);
    	frame.hide();
    	frame.setVisible(false);
    	
    	
    }
    public JPanel paintSignup()
    {
    	JPanel spanel = new JPanel();
    	spanel.setPreferredSize(new Dimension(656,375));
    	spanel.setBackground(Color.ORANGE);
    	add(spanel);
    	repaint(); 
    	return spanel;
    }
	public void windowActivated(WindowEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	public void windowClosed(WindowEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	public void windowClosing(WindowEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	public void windowDeactivated(WindowEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	public void windowDeiconified(WindowEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	public void windowIconified(WindowEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	public void windowOpened(WindowEvent arg0) {
		// TODO Auto-generated method stub
		
	}
}

